apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sangam
resources:
  - namespace.yaml
  - config.yaml
  - storage.yaml
  - migrator-job.yaml
  - identity.yaml
  - portal.yaml
  - admin.yaml
  - partner.yaml
  - ingress.yaml
  - networkpolicy.yaml
