// <auto-generated />
using System;
using Imagiqa.Web.Records;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imagiqa.Web.Records.Migrations
{
    [DbContext(typeof(ImagiqaDbContext))]
    partial class ImagiqaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("patient_mrn");

            modelBuilder.Entity("Imagiqa.Web.Records.ConsultationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("written_at");

                    b.Property<Guid>("WrittenById")
                        .HasColumnType("uuid")
                        .HasColumnName("written_by_id");

                    b.Property<string>("WrittenByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("written_by_name");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("PatientId", "WrittenAt")
                        .HasDatabaseName("ix_notes_patient_id_written_at");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Imagiqa.Web.Records.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("mobile");

                    b.Property<long>("Mrn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("mrn")
                        .HasDefaultValueSql("nextval('patient_mrn')");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<Guid>("RegisteredById")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by_id");

                    b.Property<string>("RegisteredByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("registered_by_name");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sex");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("Mrn")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_mrn");

                    b.HasIndex("OrganisationId", "RegisteredAt")
                        .HasDatabaseName("ix_patients_organisation_id_registered_at");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Imagiqa.Web.Records.VitalSigns", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Diastolic")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int?>("Pulse")
                        .HasColumnType("integer")
                        .HasColumnName("pulse");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedById")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_id");

                    b.Property<string>("RecordedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recorded_by_name");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<int?>("SpO2")
                        .HasColumnType("integer")
                        .HasColumnName("sp_o2");

                    b.Property<int?>("Systolic")
                        .HasColumnType("integer")
                        .HasColumnName("systolic");

                    b.Property<decimal?>("TemperatureC")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature_c");

                    b.HasKey("Id")
                        .HasName("pk_vitals");

                    b.HasIndex("PatientId", "RecordedAt")
                        .HasDatabaseName("ix_vitals_patient_id_recorded_at");

                    b.ToTable("vitals", (string)null);
                });

            modelBuilder.Entity("Imagiqa.Web.Records.ConsultationNote", b =>
                {
                    b.HasOne("Imagiqa.Web.Records.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_patients_patient_id");
                });

            modelBuilder.Entity("Imagiqa.Web.Records.VitalSigns", b =>
                {
                    b.HasOne("Imagiqa.Web.Records.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vitals_patients_patient_id");
                });
#pragma warning restore 612, 618
        }
    }
}
